<table>
    <thead>
    <tr>
        <th>id</th>
        <th>salary_structure_id</th>
        <th>grade_level</th>
        <th>no_of_grade_steps</th>
        <th>Step1</th>
        <th>Step2</th>
        <th>Step3</th>
        <th>Step4</th>
        <th>Step5</th>
        <th>Step6</th>
        <th>Step7</th>
        <th>Step8</th>
        <th>Step9</th>
        <th>Step10</th>
        <th>Step11</th>
        <th>Step12</th>
        <th>Step13</th>
        <th>Step14</th>
        <th>Step15</th>
        <th>Step16</th>
        <th>Step17</th>
        <th>Step18</th>
        <th>Step19</th>
        <th>Step20</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
    </thead>
    <tbody>
    @forelse($salaries as $salary)
        <tr>
            <th>{{$salary->id}}</th>
            <td>{{$salary->salary_structure_id}}</td>
            <td>{{$salary->grade_level}}</td>
            <td>{{$salary->no_of_grade_steps}}</td>
            <td>{{$salary->Step1}}</td>
            <td>{{$salary->Step2}}</td>
            <td>{{$salary->Step3}}</td>
            <td>{{$salary->Step4}}</td>
            <td>{{$salary->Step5}}</td>
            <td>{{$salary->Step6}}</td>
            <td>{{$salary->Step7}}</td>
            <td>{{$salary->Step8}}</td>
            <td>{{$salary->Step9}}</td>
            <td>{{$salary->Step10}}</td>
            <td>{{$salary->Step11}}</td>
            <td>{{$salary->Step12}}</td>
            <td>{{$salary->Step13}}</td>
            <td>{{$salary->Step14}}</td>
            <td>{{$salary->Step15}}</td>
            <td>{{$salary->Step16}}</td>
            <td>{{$salary->Step17}}</td>
            <td>{{$salary->Step18}}</td>
            <td>{{$salary->Step19}}</td>
            <td>{{$salary->Step20}}</td>
            <td>{{$salary->created_at}}</td>
            <td>{{$salary->updated_at}}</td>
        </tr>
    @empty
    @endforelse
    </tbody>
</table>
