<table>
    <thead>
   <tr>
       <th>id</th>
       <th>salary_month</th>
       <th>salary_year</th>
       <th>pf_number</th>
       <th>ip_number</th>
       <th>full_name</th>
       <th>unit</th>
       <th>department</th>
       <th>staff_category</th>
       <th>phone_number</th>
       <th>employment_type</th>
       <th>employment_status</th>
       <th>salary_structure</th>
       <th>grade_level</th>
       <th>step</th>
       <th>bank_code</th>
       <th>account_number</th>
       <th>bank_name</th>
       <th>pfa_name</th>
       <th>pension_pin</th>
       <th>basic_salary</th>
       <th>A1</th>
       <th>A2</th>
       <th>A3</th>
       <th>A4</th>
       <th>A5</th>
       <th>A6</th>
       <th>A7</th>
       <th>A8</th>
       <th>A9</th>
       <th>A10</th>
       <th>A11</th>
       <th>A12</th>
       <th>A13</th>
       <th>A14</th>
       <th>D1</th>
       <th>D2</th>
       <th>D3</th>
       <th>D4</th>
       <th>D5</th>
       <th>D6</th>
       <th>D7</th>
       <th>D8</th>
       <th>D9</th>
       <th>D10</th>
       <th>D11</th>
       <th>D12</th>
       <th>D13</th>
       <th>D14</th>
       <th>D15</th>
       <th>D16</th>
       <th>D17</th>
       <th>D18</th>
       <th>D19</th>
       <th>D20</th>
       <th>D21</th>
       <th>D22</th>
       <th>D23</th>
       <th>D24</th>
       <th>D25</th>
       <th>D26</th>
       <th>D27</th>
       <th>D28</th>
       <th>D29</th>
       <th>D30</th>
       <th>D31</th>
       <th>D32</th>
       <th>D33</th>
       <th>D34</th>
       <th>D35</th>
       <th>D36</th>
       <th>D37</th>
       <th>D38</th>
       <th>D39</th>
       <th>D40</th>
       <th>D41</th>
       <th>D42</th>
       <th>D43</th>
       <th>D44</th>
       <th>D45</th>
       <th>D46</th>
       <th>D47</th>
       <th>D48</th>
       <th>D49</th>
       <th>D50</th>
       <th>salary_areas</th>
       <th>total_allowance</th>
       <th>gross_pay</th>
       <th>total_deduction</th>
       <th>net_pay</th>
       <th>nhis</th>
       <th>employer_pension</th>
       <th>deduction_countdown</th>
       <th>salary_remark</th>
       <th>created_at</th>
       <th>updated_at</th>
       <th>date_month</th>
   </tr>
    </thead>
    <tbody>
    @foreach($histories as $history)
    <tr>
        <td>{{$history->id}}</td>
        <td>{{$history->salary_month}}</td>
        <td>{{$history->salary_year}}</td>
        <td>{{$history->pf_number}}</td>
        <td>{{$history->ip_number}}</td>
        <td>{{$history->full_name}}</td>
        <td>{{$history->unit}}</td>
        <td>{{$history->department}}</td>
        <td>{{$history->staff_category}}</td>
        <td>{{$history->phone_number}}</td>
        <td>{{$history->employment_type}}</td>
        <td>{{$history->employment_status}}</td>
        <td>{{$history->salary_structure}}</td>
        <td>{{$history->grade_level}}</td>
        <td>{{$history->step}}</td>
        <td>{{$history->bank_code}}</td>
        <td>{{$history->account_number}}</td>
        <td>{{$history->bank_name}}</td>
        <td>{{$history->pfa_name}}</td>
        <td>{{$history->pension_pin}}</td>
        <td>{{$history->basic_salary}}</td>
        <td>{{$history->A1}}</td>
        <td>{{$history->A2}}</td>
        <td>{{$history->A3}}</td>
        <td>{{$history->A4}}</td>
        <td>{{$history->A5}}</td>
        <td>{{$history->A6}}</td>
        <td>{{$history->A7}}</td>
        <td>{{$history->A8}}</td>
        <td>{{$history->A9}}</td>
        <td>{{$history->A10}}</td>
        <td>{{$history->A11}}</td>
        <td>{{$history->A12}}</td>
        <td>{{$history->A13}}</td>
        <td>{{$history->A14}}</td>
        <td>{{$history->D1}}</td>
        <td>{{$history->D2}}</td>
        <td>{{$history->D3}}</td>
        <td>{{$history->D4}}</td>
        <td>{{$history->D5}}</td>
        <td>{{$history->D6}}</td>
        <td>{{$history->D7}}</td>
        <td>{{$history->D8}}</td>
        <td>{{$history->D9}}</td>
        <td>{{$history->D10}}</td>
        <td>{{$history->D11}}</td>
        <td>{{$history->D12}}</td>
        <td>{{$history->D13}}</td>
        <td>{{$history->D14}}</td>
        <td>{{$history->D15}}</td>
        <td>{{$history->D16}}</td>
        <td>{{$history->D17}}</td>
        <td>{{$history->D18}}</td>
        <td>{{$history->D19}}</td>
        <td>{{$history->D20}}</td>
        <td>{{$history->D21}}</td>
        <td>{{$history->D22}}</td>
        <td>{{$history->D23}}</td>
        <td>{{$history->D24}}</td>
        <td>{{$history->D25}}</td>
        <td>{{$history->D26}}</td>
        <td>{{$history->D27}}</td>
        <td>{{$history->D28}}</td>
        <td>{{$history->D29}}</td>
        <td>{{$history->D30}}</td>
        <td>{{$history->D31}}</td>
        <td>{{$history->D32}}</td>
        <td>{{$history->D33}}</td>
        <td>{{$history->D34}}</td>
        <td>{{$history->D35}}</td>
        <td>{{$history->D36}}</td>
        <td>{{$history->D37}}</td>
        <td>{{$history->D38}}</td>
        <td>{{$history->D39}}</td>
        <td>{{$history->D40}}</td>
        <td>{{$history->D41}}</td>
        <td>{{$history->D42}}</td>
        <td>{{$history->D43}}</td>
        <td>{{$history->D44}}</td>
        <td>{{$history->D45}}</td>
        <td>{{$history->D46}}</td>
        <td>{{$history->D47}}</td>
        <td>{{$history->D48}}</td>
        <td>{{$history->D49}}</td>
        <td>{{$history->D50}}</td>
        <td>{{$history->salary_areas}}</td>
        <td>{{$history->total_allowance}}</td>
        <td>{{$history->gross_pay}}</td>
        <td>{{$history->total_deduction}}</td>
        <td>{{$history->net_pay}}</td>
        <td>{{$history->nhis}}</td>
        <td>{{$history->employer_pension}}</td>
        <td>{{$history->deduction_countdown}}</td>
        <td>{{$history->salary_remark}}</td>
        <td>{{$history->created_at}}</td>
        <td>{{$history->updated_at}}</td>
        <td>{{$history->date_month}}</td>
    </tr>
    @endforeach
    </tbody>
</table>
