<table>
    <thead>
    <tr>
        <th>id</th>
        <th>employee_id</th>
        <th>basic_salary</th>
        <th>A1</th>
        <th>A2</th>
        <th>A3</th>
        <th>A4</th>
        <th>A5</th>
        <th>A6</th>
        <th>A7</th>
        <th>A8</th>
        <th>A9</th>
        <th>A10</th>
        <th>A11</th>
        <th>A12</th>
        <th>A13</th>
        <th>A14</th>
        <th>D1</th>
        <th>D2</th>
        <th>D3</th>
        <th>D4</th>
        <th>D5</th>
        <th>D6</th>
        <th>D7</th>
        <th>D8</th>
        <th>D9</th>
        <th>D10</th>
        <th>D11</th>
        <th>D12</th>
        <th>D13</th>
        <th>D14</th>
        <th>D15</th>
        <th>D16</th>
        <th>D17</th>
        <th>D18</th>
        <th>D19</th>
        <th>D20</th>
        <th>D21</th>
        <th>D22</th>
        <th>D23</th>
        <th>D24</th>
        <th>D25</th>
        <th>D26</th>
        <th>D27</th>
        <th>D28</th>
        <th>D29</th>
        <th>D30</th>
        <th>D31</th>
        <th>D32</th>
        <th>D33</th>
        <th>D34</th>
        <th>D35</th>
        <th>D36</th>
        <th>D37</th>
        <th>D38</th>
        <th>D39</th>
        <th>D40</th>
        <th>D41</th>
        <th>D42</th>
        <th>D43</th>
        <th>D44</th>
        <th>D45</th>
        <th>D46</th>
        <th>D47</th>
        <th>D48</th>
        <th>D49</th>
        <th>D50</th>
        <th>salary_arears</th>
        <th>gross_pay</th>
        <th>total_allowance</th>
        <th>total_deduction</th>
        <th>net_pay</th>
        <th>nhis</th>
        <th>employer_pension</th>
        <th>deduction_countdown</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>
    </thead>
    <tbody>
    @foreach($salaries as $salary)
      <tr>
          <td>{{$salary->id}}</td>
          <td>{{$salary->employee_id}}</td>
          <td>{{$salary->basic_salary}}</td>
          <td>{{$salary->A1}}</td>
          <td>{{$salary->A2}}</td>
          <td>{{$salary->A3}}</td>
          <td>{{$salary->A4}}</td>
          <td>{{$salary->A5}}</td>
          <td>{{$salary->A6}}</td>
          <td>{{$salary->A7}}</td>
          <td>{{$salary->A8}}</td>
          <td>{{$salary->A9}}</td>
          <td>{{$salary->A10}}</td>
          <td>{{$salary->A11}}</td>
          <td>{{$salary->A12}}</td>
          <td>{{$salary->A13}}</td>
          <td>{{$salary->A14}}</td>
          <td>{{$salary->D1}}</td>
          <td>{{$salary->D2}}</td>
          <td>{{$salary->D3}}</td>
          <td>{{$salary->D4}}</td>
          <td>{{$salary->D5}}</td>
          <td>{{$salary->D6}}</td>
          <td>{{$salary->D7}}</td>
          <td>{{$salary->D8}}</td>
          <td>{{$salary->D9}}</td>
          <td>{{$salary->D10}}</td>
          <td>{{$salary->D11}}</td>
          <td>{{$salary->D12}}</td>
          <td>{{$salary->D13}}</td>
          <td>{{$salary->D14}}</td>
          <td>{{$salary->D15}}</td>
          <td>{{$salary->D16}}</td>
          <td>{{$salary->D17}}</td>
          <td>{{$salary->D18}}</td>
          <td>{{$salary->D19}}</td>
          <td>{{$salary->D20}}</td>
          <td>{{$salary->D21}}</td>
          <td>{{$salary->D22}}</td>
          <td>{{$salary->D23}}</td>
          <td>{{$salary->D24}}</td>
          <td>{{$salary->D25}}</td>
          <td>{{$salary->D26}}</td>
          <td>{{$salary->D27}}</td>
          <td>{{$salary->D28}}</td>
          <td>{{$salary->D29}}</td>
          <td>{{$salary->D30}}</td>
          <td>{{$salary->D31}}</td>
          <td>{{$salary->D32}}</td>
          <td>{{$salary->D33}}</td>
          <td>{{$salary->D34}}</td>
          <td>{{$salary->D35}}</td>
          <td>{{$salary->D36}}</td>
          <td>{{$salary->D37}}</td>
          <td>{{$salary->D38}}</td>
          <td>{{$salary->D39}}</td>
          <td>{{$salary->D40}}</td>
          <td>{{$salary->D41}}</td>
          <td>{{$salary->D42}}</td>
          <td>{{$salary->D43}}</td>
          <td>{{$salary->D44}}</td>
          <td>{{$salary->D45}}</td>
          <td>{{$salary->D46}}</td>
          <td>{{$salary->D47}}</td>
          <td>{{$salary->D48}}</td>
          <td>{{$salary->D49}}</td>
          <td>{{$salary->D50}}</td>
          <td>{{$salary->salary_arears}}</td>
          <td>{{$salary->gross_pay}}</td>
          <td>{{$salary->total_allowance}}</td>
          <td>{{$salary->total_deduction}}</td>
          <td>{{$salary->net_pay}}</td>
          <td>{{$salary->nhis}}</td>
          <td>{{$salary->employer_pension}}</td>
          <td>{{$salary->deduction_countdown}}</td>
          <td>{{$salary->created_at}}</td>
          <td>{{$salary->updated_at}}</td>
      </tr>
    @endforeach
    </tbody>
</table>
