<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SalaryUpdate extends Model
{
    use HasFactory;
    protected $fillable=[
        'id',
        'employee_id',
        'basic_salary',
        'A1',
        'A2',
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'A9',
        'A10',
        'A11',
        'A12',
        'A13',
        'A14',
        'D1',
        'D2',
        'D3',
        'D4',
        'D5',
        'D6',
        'D7',
        'D8',
        'D9',
        'D10',
        'D11',
        'D12',
        'D13',
        'D14',
        'D15',
        'D16',
        'D17',
        'D18',
        'D19',
        'D20',
        'D21',
        'D22',
        'D23',
        'D24',
        'D25',
        'D26',
        'D27',
        'D28',
        'D29',
        'D30',
        'D31',
        'D32',
        'D33',
        'D34',
        'D35',
        'D36',
        'D37',
        'D38',
        'D39',
        'D40',
        'D41',
        'D42',
        'D43',
        'D44',
        'D45',
        'D46',
        'D47',
        'D48',
        'D49',
        'D50',
        'salary_arears',
        'gross_pay',
        'total_allowance',
        'total_deduction',
        'net_pay',
        'deduction_countdown',
        'created_at',
        'updated_at',
        'nhis',
        'employer_pension'
    ];
}
